重载SetIcon,添加faw::string_t参数的SetIcon函数,通过加载icon路径设置任务栏图标
fawdlstty/DuiLib_Faw pull request #17
Opened 2022-10-06 13:52 UTC by wuwao1

demo.ico放在当前工作目录下可以使用`SetIcon("demo.ico")`,设置demo.ico为程序图标

2022-10-06 14:33 UTC, fawdlstty commented
感谢prprpr。加载当前目录似乎不太合适，改为加载资源目录或资源压缩包里的相对地址实现更好

2022-10-06 15:02 UTC, wuwao1 commented
只是举个例子呀,放在skin目录下加载 `SetIcon("skin\\demo.ico")`也是可以的

2022-10-06 15:09 UTC, fawdlstty commented
口误，从工作目录加载不太合适。资源统一调配比较好，比如统一从某个资源路径加载，或者统一从资源压缩包里加载

2022-10-08 10:58 UTC, wuwao1 commented
测试图片放在在zip压缩包和资源文件夹下都能正常工作,支持png,bmp,ico

2022-10-11 04:30 UTC, wuwao1 commented
@fawdlstty Done,please help to review this PR. Thanks.

2022-10-11 07:45 UTC, fawdlstty requested changes

2022-10-11 07:45 UTC, fawdlstty commented on DuiLib/Core/UIBase.cpp
> +		static HICON icon_handle = NULL;
静态变量会导致多个实例图标冲突，如果需要缓存可考虑修改为类成员变量

2022-10-11 16:15 UTC, wuwao1 commented on DuiLib/Core/UIBase.cpp
> +		static HICON icon_handle = NULL;
issue fixed in the latest commit

2022-10-13 03:25 UTC, wuwao1 commented on DuiLib/Core/UIBase.cpp
> +		static HICON icon_handle = NULL;
@fawdlstty

2022-10-13 14:49 UTC, fawdlstty approved these changes

2022-10-13 14:49 UTC, merged